default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: OneBitFood_development


test:
  <<: *default
  database: OneBitFood_test
 

production:
  <<: *default
  database: OneBitFood_production
  username: OneBitFood
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>